In [1]:
import numpy as np

In [2]:
my_array = np.asarray(range(0,20)).reshape(4,5)
print(my_array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [3]:
new_array = my_array.transpose(1,0) # returns a reshaped array, does not modify original my_array
print(new_array)

[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


In [4]:
my_array -= 1
print(my_array)
print(new_array) # new array is still referencing original array; use .copy() to create a new one

[[-1  0  1  2  3]
 [ 4  5  6  7  8]
 [ 9 10 11 12 13]
 [14 15 16 17 18]]
[[-1  4  9 14]
 [ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]]


In [26]:
my_3d_array = np.asarray(range(0,24)).reshape(2,3,4)
print(my_3d_array)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [6]:
# Axis
np.sum(my_array, axis=0) # sum, collapsing axis 0 (rows) into one row


array([26, 30, 34, 38, 42])

In [7]:
np.sum(my_array, axis=1) # sum, collapsing axis 1 (columns) into one column


array([ 5, 30, 55, 80])

In [8]:
# Get first two rows, from 4th column to the end
my_array[0:2, 3:]


array([[2, 3],
       [7, 8]])

In [9]:
# Get every other row, start at last column and go backward
my_array[::2, -1::-1]


array([[ 3,  2,  1,  0, -1],
       [13, 12, 11, 10,  9]])

In [10]:
# Get indices for all rows that have a 5 in them
row_idx = np.where(my_array==5)[0]
print(row_idx)
my_array[row_idx]

[1]


array([[4, 5, 6, 7, 8]])

In [11]:
# Multiply
my_array * my_array

array([[  1,   0,   1,   4,   9],
       [ 16,  25,  36,  49,  64],
       [ 81, 100, 121, 144, 169],
       [196, 225, 256, 289, 324]])

In [12]:
# Matrix Multiply
np.matmul(my_array, my_array.transpose())

array([[  15,   40,   65,   90],
       [  40,  190,  340,  490],
       [  65,  340,  615,  890],
       [  90,  490,  890, 1290]])

In [20]:
my_array[0][4] -= 3
my_array[3][0] -= 8
print(my_array)
np.max(my_array, axis=1) # get maximum element of each row -- collapsing columns (axis=1) into 1 column

[[-1  0  1  2 -3]
 [ 4  5  6  7  8]
 [ 9 10 11 12 13]
 [ 3 15 16 17 18]]


array([ 2,  8, 13, 18])

In [21]:
np.max(my_array, axis=0) # get maximum element of each column -- collapsing rows (axis=0) into 1 row

array([ 9, 15, 16, 17, 18])

In [31]:
# Axis in 3d
print(my_3d_array)
np.max(my_3d_array, axis=1)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


array([[ 8,  9, 10, 11],
       [20, 21, 22, 23]])

In [15]:
np.maximum(my_array, my_array*2)

array([[-1,  0,  2,  4,  0],
       [ 8, 10, 12, 14, 16],
       [18, 20, 22, 24, 26],
       [22, 30, 32, 34, 36]])

In [16]:
np.random.randn(4,4)

array([[-0.41677369, -1.72321967, -0.27903766, -0.10283593],
       [-0.71881853,  1.22317472, -0.56927886, -0.68720286],
       [ 1.92655114,  1.64798685, -0.1221865 ,  0.77999633],
       [ 0.50633223, -0.51956778, -0.91223317,  1.49921368]])

In [17]:
my_array.shape

(4, 5)

In [18]:
np.random.randint(0,5,10) # min, max, dimension

array([0, 2, 4, 3, 0, 0, 3, 2, 1, 0])

In [19]:
np.random.randn(10) # sample 10x from standard normal

array([ 0.72816686,  0.32857971,  0.51808735,  0.67634138, -0.31187088,
       -0.31187119, -1.35956618,  0.04100348, -0.17581134,  0.93870556])